/** 
[INFO]
ITEM_INFO 게임에서 사용되는 아이템 정보
ITEM_ID, ITEM_NAME, RARITY, PRICE

ITEM_TREE 아이템 관계
ITEM_ID, PARENT_ITEM_ID

ROOT 아이템의 PARENT 아이템 ID는 NULL

[OUTPUT]
ROOT 아이템을 찾아 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME)을 출력하는 SQL문
아이템 ID ASC
*/

SELECT ITEM_ID, ITEM_NAME
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID
      FROM ITEM_TREE
      WHERE PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID ASC
