/*
CART_PRODUCTS 장바구니에 담긴 상품 정보
ID, CART_ID, NAME, PRICE

우유와 요거트를 동시에 구입한 장바구니의 아이디를 조회

[결과]
CART_ID asc
*/

/* 방법 1 */
# SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE NAME IN ('Milk', 'Yogurt')
# GROUP BY CART_ID
# HAVING COUNT(DISTINCT NAME) = 2
# ORDER BY CART_ID ASC;

/* 방법 2 */
# WITH HAS_MILK AS (
#     SELECT DISTINCT CART_ID, NAME
#     FROM CART_PRODUCTS
#     WHERE NAME = 'Milk'
# ),

# HAS_YOGURT AS (
#     SELECT DISTINCT CART_ID, NAME
#     FROM CART_PRODUCTS
#     WHERE NAME = 'Yogurt'
# )

# SELECT M.CART_ID
# FROM HAS_MILK AS M
# JOIN HAS_YOGURT AS Y
#     ON M.CART_ID = Y.CART_ID
# ORDER BY M.CART_ID ASC;

/* 방법 3 */
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING GROUP_CONCAT(NAME) LIKE '%Yogurt%' AND GROUP_CONCAT(NAME) LIKE '%Milk%'
ORDER BY CART_ID ASC;