/*
ECOLI_DATA 실험실에서 배양한 대장균들의 정보
ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE

최초의 대장균 개체의 PARENT_ID 는 NULL 값

3세대의 대장균의 ID(ID) 를 출력
대장균의 ID 에 대해 오름차순 정렬
*/
# SELECT ID 
# FROM ECOLI_DATA
# WHERE PARENT_ID IN (
#     SELECT ID 
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IN (
#         SELECT ID
#         FROM ECOLI_DATA
#         WHERE PARENT_ID IS NULL
#     )
# )
# ORDER BY ID ASC


# SELECT ED1.ID AS ID
# FROM ECOLI_DATA AS ED1
# JOIN ECOLI_DATA AS ED2 
#     ON ED1.PARENT_ID = ED2.ID
# JOIN ECOLI_DATA AS ED3
#     ON ED2.PARENT_ID = ED3.ID
# WHERE ED3.PARENT_ID IS NULL
# ORDER BY ED1.ID ASC

WITH RECURSIVE ANCESTORS AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, AN.GEN+1 AS GEN
    FROM ECOLI_DATA AS ED
    INNER JOIN ANCESTORS AS AN 
        ON ED.PARENT_ID = AN.ID
)

SELECT ID
FROM ANCESTORS
WHERE GEN = 3
ORDER BY ID ASC;