/*
ECOLI_DATA 실험실에서 배양한 대장균들의 정보
ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE

최초의 대장균 개체의 PARENT_ID 는 NULL 

대장균 개체의 ID(ID)와 자식의 수(CHILD_COUNT)를 출력
자식이 없다면 자식의 수는 0
개체의 ID 에 대해 오름차순 정렬
*/

SELECT ED1.ID, IFNULL(ED2.AMOUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS ED1
LEFT JOIN (
    SELECT PARENT_ID, COUNT(ID) AS AMOUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
) AS ED2
ON ED1.ID = ED2.PARENT_ID
ORDER BY ED1.ID