/*
ANIMAL_INS 동물 보호소에 들어온 동물의 정보
ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE

ANIMAL_OUTS 동물 보호소에서 입양을 보낸 동물의 정보
ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_OUTCOME

보호소에 들어올 당시에는 중성화 되지 않았지만, 
보호소를 나갈 당시에는 중성화된 동물의 
아이디와 생물 종, 이름을 조회하는 아이디 순으로 조회
*/

# SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
# FROM ANIMAL_INS AS INS
# JOIN ANIMAL_OUTS AS OUTS
# ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE INS.SEX_UPON_INTAKE LIKE "INTACT%" AND 
# ( SEX_UPON_OUTCOME LIKE "SPAYED%" OR SEX_UPON_OUTCOME LIKE "Neutered%" )
# ORDER BY INS.ANIMAL_ID

SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE 
    ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID 
    AND
    SEX_UPON_INTAKE LIKE "INTACT%" 
    AND 
    ( SEX_UPON_OUTCOME LIKE "SPAYED%" OR SEX_UPON_OUTCOME LIKE "Neutered%" )
ORDER BY ANIMAL_INS.ANIMAL_ID