/*
USER_INFO 의류 쇼핑몰에 가입한 회원 정보
USER_ID, GENDER, AGE, JOINED

ONLINE_SALE 온라인 상품 판매 정보
ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE

[조회] 년, 월, 성별 별로 상품을 구매한 회원수를 집계

[결과]
년 -> 월 -> 성별을 기준으로 오름차순 정렬
이때, 성별 정보가 없는 경우 결과에서 제외
*/

SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE AS OS
INNER JOIN (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) AS UI
    ON UI.USER_ID = OS.USER_ID
GROUP BY YEAR, MONTH, UI.GENDER
ORDER BY YEAR, MONTH, UI.GENDER;
