/*
[INFO]
MEMBER_PROFILE 고객의 정보
MEMBER_ID, MEMBER_NAME, TLNO, GENDER, DATE_OF_BIRTH

REST_REVIEW 식당의 리뷰 정보
REVIEW_ID, REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT,REVIEW_DATE

[?] MEMBER_PROFILE와 REST_REVIEW 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회

[OUTPUT]
- 회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력
- 리뷰 작성일을 기준으로 오름차순, 리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차순 정렬
*/

# WITH TopMembers AS (
#     SELECT MP.MEMBER_ID
#     FROM MEMBER_PROFILE AS MP
#     JOIN REST_REVIEW AS RR 
#     ON MP.MEMBER_ID = RR.MEMBER_ID
#     GROUP BY MP.MEMBER_ID
#     ORDER BY COUNT(RR.REVIEW_ID) DESC
#     LIMIT 1
# )
# SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE AS MP
# JOIN REST_REVIEW AS RR 
# ON MP.MEMBER_ID = RR.MEMBER_ID
# JOIN TopMembers TM
# ON MP.MEMBER_ID = TM.MEMBER_ID
# ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR 
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC