/*
HR_DEPARTMENT 회사의 부서 정보
DEPT_ID, DEPT_NAME_KR, DEPT_NAME_EN, LOCATION

HR_EMPLOYEES 회사의 사원 정보
MP_NO, EMP_NAME, DEPT_ID, POSITION, EMAIL, COMP_TEL, HIRE_DATE, SAL

부서별 평균 연봉을 조회
-> 부서별로 부서 ID, 영문 부서명, 평균 연봉을 조회

평균연봉(AVG_SAL) : 소수점 첫째 자리에서 반올림
부서별 평균 연봉을 기준으로 내림차순 정렬
*/

SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS HD
INNER JOIN HR_EMPLOYEES AS HE
    ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC;


